# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1k4-iqSg68l8j6or-aFNMlrE8DyqOTP
"""

# app.py
import streamlit as st
import pandas as pd
import joblib
import numpy as np

# Load the trained model
@st.cache_resource
def load_model():
    model = joblib.load('titanic_survival_model.pkl')
    return model

model = load_model()

# App title and description
st.title('🚢 Titanic Survival Predictor')
st.write('Enter passenger details to predict survival probability')

st.markdown('---')

# Create input form
st.subheader('Passenger Information')

col1, col2 = st.columns(2)

with col1:
    pclass = st.selectbox('Passenger Class', [1, 2, 3],
                         help='1 = First Class, 2 = Second Class, 3 = Third Class')
    sex = st.selectbox('Gender', ['Male', 'Female'])
    age = st.slider('Age', 0, 80, 25)

with col2:
    sibsp = st.number_input('Number of Siblings/Spouses Aboard', 0, 8, 0)
    parch = st.number_input('Number of Parents/Children Aboard', 0, 6, 0)
    fare = st.number_input('Fare (in £)', 0.0, 500.0, 50.0, step=1.0)

st.markdown('---')

# Predict button
if st.button('🔮 Predict Survival', type='primary'):
    # Prepare input data
    sex_encoded = 1 if sex == 'Male' else 0

    input_data = pd.DataFrame({
        'Pclass': [pclass],
        'Sex': [sex_encoded],
        'Age': [age],
        'SibSp': [sibsp],
        'Parch': [parch],
        'Fare': [fare]
    })

    # Make prediction
    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0]

    # Display results
    st.subheader('Prediction Results')

    if prediction == 1:
        st.success(f'✅ **SURVIVED** with {probability[1]*100:.1f}% confidence')
        st.balloons()
    else:
        st.error(f'❌ **DID NOT SURVIVE** with {probability[0]*100:.1f}% confidence')

    # Show input summary
    st.markdown('---')
    st.subheader('Input Summary')
    st.write(f'**Class:** {pclass} | **Gender:** {sex} | **Age:** {age}')
    st.write(f'**Family:** {sibsp} siblings/spouses, {parch} parents/children')
    st.write(f'**Fare:** £{fare:.2f}')

# Sidebar with info
st.sidebar.title('About')
st.sidebar.info(
    'This app uses a Random Forest model trained on Titanic passenger data '
    'to predict survival probability. The model achieved **83.84% accuracy** '
    'using cross-validation.'
)

st.sidebar.markdown('---')
st.sidebar.subheader('Model Details')
st.sidebar.write('**Algorithm:** Random Forest')
st.sidebar.write('**Accuracy:** 83.84%')
st.sidebar.write('**Features:** 6')
st.sidebar.write('**Training Samples:** 891')

st.sidebar.markdown('---')
st.sidebar.caption('Built by [Eric]')
st.sidebar.caption('GitHub: [e-ric79](https://github.com/e-ric79)')